# Generated by Django 4.1.5 on 2023-01-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
