# Generated by Django 4.1.5 on 2023-01-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
