# Generated by Django 4.1.5 on 2023-01-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
